### ISSUE TITLE
hvsrinv

### ISSUE THREAD

**Issue by sayedmohamed92** [ozkankafadar/HVSRInv#1]
the hvsrinv.exe file not found

**Comment by ozkankafadar** [comment]
Dear Sayed Mohamed Ali Hussein Mohamed,
Thank you for this information. I will upload the exe file today. I am sorry for this lack.
Best regards.

iPhone’umdan gönderildi

Sayed Mohamed Ali Hussein Mohamed ***@***.***> şunları yazdı (2 Şub 2022 13:46):

**Comment by sayedmohamed92** [comment]
Thanks for uploading exe file.
