### ISSUE TITLE
HVSRInv Start.m Window Error

### ISSUE THREAD

**Issue by annikagoozen** [ozkankafadar/HVSRInv#2]
When I run the start.m and the InverseModeling.m files, the HVSRInv windows don't expand all the way. They also don't let me alter the size of the window so I can't use the program. SOS plz. I'm on a Mac using Matlab2022b. 
<img width="1249" alt="Screenshot 2023-11-15 at 6 54 28 PM" src="https://github.com/ozkankafadar/HVSRInv/assets/145499458/1a163ede-0883-4dd2-972d-7c1f57c5e4db">
<img width="576" alt="Screenshot 2023-11-15 at 6 54 18 PM" src="https://github.com/ozkankafadar/HVSRInv/assets/145499458/08cba537-5263-4d49-b34d-ff3cf4cbefa9">

**Comment by ozkankafadar** [comment]
Dear ?,

I will inform you about this issue soon.

Best regards,

Assoc. Prof. Dr. Özkan Kafadar
Department of Construction Technology
Kocaeli University, Turkey

**Comment by ozkankafadar** [comment]
Did you try to use the following command?
get(0,'screensize')

Assoc. Prof. Dr. Özkan Kafadar
Department of Construction Technology
Kocaeli University, Turkey

**Comment by ozkankafadar** [comment]
Besides, I set the unit property of the windows as "pixel". You can change
the unit property of the windows as "normalized", and try it again.

Assoc. Prof. Dr. Özkan Kafadar
Department of Construction Technology
Kocaeli University, Turkey

**Comment by annikagoozen** [comment]
I used the 'guide' command to open each .fig, from there I changed the sizes of each window and changed them from pixel to proportional under 'Tools' and 'GUI Options'. It's working great now, thank you for your help! :)
